= dunaj-starter

A starter leiningen project for http://dunaj.org[Dunaj]

== Requirements

* Oracle JDK 8
* Leiningen
* Git

== Usage

. Clone this repository with `git clone https://github.com/dunaj-project/dunaj-starter.git`
. Run REPL with `lein repl`
. In REPL, eval `(dunaj!)` to start working with Dunaj

To use Dunaj in your sources, use `:api` ns declaration:

[source,clojure,linesnum]
--
(ns dunaj-starter.core
  "See http://dunaj.org for documentation and examples"
  (:api dunaj))

(defn bar :- String
  [s :- String]
  (str (print "Hello %s!" s)))

(defn foo :- nil
  [s :- String]
  (println! (bar s))
  nil)

(foo "World")
--

See http://dunaj.org[Dunaj homepage] for documentation and examples.

== License

Copyright © 2013, 2015, Jozef Wagner.

The use and distribution terms for this software are covered by the [Eclipse Public License 1.0](http://opensource.org/licenses/eclipse-1.0.php) which can be found in the file epl-v10.html at the root of this distribution.

By using this software in any fashion, you are agreeing to be bound by the terms of this license.

You must not remove this notice, or any other, from this software.
